SET CLIENT_ENCODING TO 'utf8';

CREATE TABLE USUARIO(
  LOGIN varchar(50) NOT NULL,
  SENHA varchar(250) NOT NULL,
  UNIQUE(LOGIN)
);

CREATE TABLE CONTATO(
  ID_CONTATO serial NOT NULL,
  NOME varchar(50) NOT NULL,
  DATA_NASC date DEFAULT NULL,
  LOGIN varchar(50) DEFAULT NULL,
  IMAGEM varchar(40) DEFAULT NULL,
  UNIQUE(ID_CONTATO),
  FOREIGN KEY(LOGIN)
    REFERENCES USUARIO(LOGIN)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);


CREATE TABLE ENDERECOS (
  ID_ENDERECO serial NOT NULL,
  RUA varchar(30) NOT NULL,
  NUMERO int NOT NULL,
  BAIRRO varchar(30) NOT NULL,
  CIDADE varchar(30) NOT NULL,
  CEP varchar(12) DEFAULT NULL,
  UNIQUE(ID_ENDERECO)
);

CREATE TABLE CONTATO_ENDERECO (
  ID_CONTATO serial NOT NULL,
  ID_ENDERECO serial NOT NULL,
  FOREIGN KEY(ID_CONTATO)
    REFERENCES CONTATO(ID_CONTATO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY(ID_ENDERECO)
    REFERENCES ENDERECOS(ID_ENDERECO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE EMAILS (
  END_EMAIL varchar(50) NOT NULL,
  ID_CONTATO serial NOT NULL,
  FOREIGN KEY(ID_CONTATO)
    REFERENCES CONTATO(ID_CONTATO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE TELEFONES (
  TELEFONE varchar(20) NOT NULL,
  ID_CONTATO serial NOT NULL,
  FOREIGN KEY(ID_CONTATO)
    REFERENCES CONTATO(ID_CONTATO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

ALTER TABLE CONTATO
  ADD PRIMARY KEY (ID_CONTATO);

ALTER TABLE CONTATO_ENDERECO
  ADD PRIMARY KEY (ID_CONTATO,ID_ENDERECO);

ALTER TABLE EMAILS
  ADD PRIMARY KEY (END_EMAIL);

ALTER TABLE ENDERECOS
  ADD PRIMARY KEY (ID_ENDERECO);

ALTER TABLE TELEFONES
  ADD PRIMARY KEY (TELEFONE);

ALTER TABLE USUARIO
  ADD PRIMARY KEY (LOGIN);

COMMIT;